#include <iostream>
#include <fstream>
#include <string>
#include "Eigen/Dense"
#include "OutputGenerator.h"

OutputGenerator::OutputGenerator(OutputData output) : out(output) {}

std::string outToHTML(const Eigen::VectorXcd & vec) {
    std::string html = "<p style=\"text-align: center;\">";
    for (int i = 0; i < vec.size(); ++i) {
        html += "λ" + std::to_string(i + 1) + " = "
            + std::to_string(vec[i].real()) + " + i" + std::to_string(vec[i].imag());
        if (i < vec.size() - 1) {
            html += ", ";
        }
    }
    html += "</p>";
    return html;
}

void OutputGenerator::saveOutput() {
    std::cout << "Saving output file..." << std::endl;

    std::ofstream htmlFile("../output.html");

    htmlFile << R"(
    <!DOCTYPE html>
    <html>
    <head>
        <title>Eigenvalue Results</title>
        <style>
            body { font-family: Arial, sans-serif; }
            table { border-collapse: collapse; width: 50%; margin: 20px auto; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: center; }
            th { background-color: #f4f4f4; }
            img { display: block; margin: 20px auto; max-width: 80%; }
        </style>
    </head>
    <body>
        <h1 style="text-align: center;">Eigenvalue Computation Results</h1>
        <h2 style="text-align: center;">Eigenvalues</h2>
    )";
    htmlFile << outToHTML(out.estimated_eigenvalues);

    htmlFile << R"(
        <h2 style="text-align: center;">Metrics</h2>
        <table>
            <tr>
                <th>Metric</th>
                <th>Value</th>
            </tr>
    )";

    htmlFile << "<tr><td>Method</td><td>" + out.method + "</td></tr>";
    htmlFile << "<tr><td>Estimated Error</td><td>" + std::to_string(out.estimated_error) + "</td></tr>";
    htmlFile << "<tr><td>Execution Time</td><td>" + std::to_string(out.execution_time) + " microseconds</td></tr>";
    htmlFile << "<tr><td>Iterations</td><td>" + std::to_string(out.iterations) + "</td></tr>";

    htmlFile << R"(
        </table>
        <h2 style="text-align: center;">Plot</h2>
        <img src="eigenvalues_plot.png" alt="Eigenvalues Plot">

        <p style="text-align: center;">Generated by C++ Program</p>
    </body>
    </html>
    )";

    htmlFile.close();
    std::cout << "HTML output saved to output.html" << std::endl;
}
